const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.GD_SDK,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Fade: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Pin: 0},
	{LiveFont3: 0},
	{LiveFont4: 0},
	{Sprite14: 0},
	{LiveFont5: 0},
	{shot1: 0},
	{shot2: 0},
	{shot3: 0},
	{shot4: 0},
	{shot5: 0},
	{Sprite24: 0},
	{LiveFont6: 0},
	{LiveFont7: 0},
	{Sprite26: 0},
	{Touch: 0},
	{Particles: 0},
	{Rotate: 0},
	{Rueda: 0},
	{shot13: 0},
	{shot14: 0},
	{shot15: 0},
	{Bullet: 0},
	{piece1: 0},
	{piece4: 0},
	{piece5: 0},
	{Sprite16: 0},
	{piece2: 0},
	{piece6: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite27: 0},
	{fontmoney1: 0},
	{LiveFont9: 0},
	{LiteTween: 0},
	{Sprite19: 0},
	{ruedas: 0},
	{Sprite21: 0},
	{Audio: 0},
	{Particles2: 0},
	{Browser: 0},
	{home: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{selector: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Sprite58: 0},
	{RotateScreen: 0},
	{Sprite60: 0},
	{Particles5: 0},
	{Sprite68: 0},
	{Sprite70: 0},
	{Particles6: 0},
	{Keyboard: 0},
	{Sprite73: 0},
	{Particles7: 0},
	{LiveFont10: 0},
	{p1: 0},
	{p2: 0},
	{p3: 0},
	{p4: 0},
	{p5: 0},
	{p6: 0},
	{p7: 0},
	{Sprite78: 0},
	{LiveFont11: 0},
	{Sprite7: 0},
	{Sprite23: 0},
	{Sprite79: 0},
	{s49: 0},
	{s52: 0},
	{s55: 0},
	{s61: 0},
	{s62: 0},
	{s63: 0},
	{s64: 0},
	{s66: 0},
	{s67: 0},
	{s69: 0},
	{s70: 0},
	{s71: 0},
	{s72: 0},
	{restart2: 0},
	{Sprite80: 0},
	{Sprite81: 0},
	{s73: 0},
	{s74: 0},
	{s75: 0},
	{Sprite87: 0},
	{Physics: 0},
	{Sprite89: 0},
	{Sprite90: 0},
	{pinner: 0},
	{Sprite92: 0},
	{Sprite93: 0},
	{Particles8: 0},
	{Particles9: 0},
	{Particles10: 0},
	{Particles11: 0},
	{Particles12: 0},
	{Particles13: 0},
	{Sprite94: 0},
	{Sprite95: 0},
	{Sprite96: 0},
	{Sprite97: 0},
	{Sprite98: 0},
	{LiveFont12: 0},
	{LiveFont13: 0},
	{ScrollTo: 0},
	{Sprite88: 0},
	{Sprite107: 0},
	{Sprite108: 0},
	{Sprite91: 0},
	{Sprite114: 0},
	{Sprite115: 0},
	{Sprite116: 0},
	{Sprite117: 0},
	{LiveFont14: 0},
	{LiveFont15: 0},
	{Sprite118: 0},
	{Sprite119: 0},
	{Sprite120: 0},
	{Sprite121: 0},
	{Sprite122: 0},
	{Sprite123: 0},
	{LiveFont16: 0},
	{soundsprite: 0},
	{walksprite: 0},
	{Sine2: 0},
	{Sprite138: 0},
	{Sprite139: 0},
	{Particles14: 0},
	{Particles15: 0},
	{p8: 0},
	{p9: 0},
	{p10: 0},
	{p11: 0},
	{p12: 0},
	{p13: 0},
	{RESET: 0},
	{YES: 0},
	{NO: 0},
	{mira: 0},
	{Solid: 0},
	{Sprite20: 0},
	{Particles16: 0},
	{Particles17: 0},
	{Sprite69: 0},
	{Sprite71: 0},
	{Sprite82: 0},
	{Sprite83: 0},
	{sangre3: 0},
	{sangre1: 0},
	{sangre2: 0},
	{Sprite2: 0},
	{Sprite84: 0},
	{fonder: 0},
	{continue: 0},
	{cancel: 0},
	{restarted: 0},
	{freemoney: 0},
	{fonder2: 0},
	{continue2: 0},
	{cancel2: 0},
	{restarted2: 0},
	{Sprite85: 0},
	{Sprite86: 0},
	{Sprite111: 0},
	{Particles18: 0},
	{Sprite129: 0},
	{redbullet: 0},
	{Sprite130: 0},
	{Sprite134: 0},
	{Sprite146: 0},
	{Sprite147: 0},
	{Sprite148: 0},
	{Sprite150: 0},
	{Sprite152: 0},
	{Sprite156: 0},
	{Sprite157: 0},
	{Sprite158: 0},
	{Sprite162: 0},
	{LiveFont17: 0},
	{Sprite167: 0},
	{Sprite176: 0},
	{Sprite189: 0},
	{Sprite194: 0},
	{Sprite195: 0},
	{Sprite196: 0},
	{Sprite197: 0},
	{Sprite199: 0},
	{Sprite200: 0},
	{Sprite201: 0},
	{Sprite202: 0},
	{Sprite203: 0},
	{Sprite204: 0},
	{Sprite205: 0},
	{Sprite206: 0},
	{Sprite207: 0},
	{Sprite208: 0},
	{Sprite209: 0},
	{Sprite222: 0},
	{Sprite223: 0},
	{Sprite224: 0},
	{freemoney2: 0},
	{Sprite229: 0},
	{Sprite230: 0},
	{moneyhud1: 0},
	{moneyhud2: 0},
	{fontmoney2: 0},
	{Sprite231: 0},
	{bulletcouns: 0},
	{Sprite239: 0},
	{Sprite240: 0},
	{Sprite236: 0},
	{Sprite241: 0},
	{Sprite242: 0},
	{POWER1: 0},
	{POWER2: 0},
	{Sprite250: 0},
	{Sprite251: 0},
	{Sprite252: 0},
	{Particles19: 0},
	{tocador: 0},
	{contador: 0},
	{Sprite256: 0},
	{Sprite257: 0},
	{Sprite259: 0},
	{Sprite260: 0},
	{Sprite261: 0},
	{paricreyas: 0},
	{paricreyas2: 0},
	{Particles20: 0},
	{lavas: 0},
	{lavavida: 0},
	{Sprite265: 0},
	{Sprite270: 0},
	{perdedor: 0},
	{Sprite59: 0},
	{MenuLightFlare: 0},
	{Sprite243: 0},
	{Sprite246: 0},
	{Sprite249: 0},
	{Sprite295: 0},
	{Sprite296: 0},
	{Sprite297: 0},
	{Sprite298: 0},
	{Sprite299: 0},
	{Sprite300: 0},
	{Sprite301: 0},
	{Sprite66: 0},
	{Sprite72: 0},
	{tuto: 0},
	{rededor: 0},
	{tuto2: 0},
	{tuto3: 0},
	{tuto4: 0},
	{restarted3: 0},
	{Sprite142: 0},
	{Sprite144: 0},
	{Sprite145: 0},
	{Sprite149: 0},
	{Sprite151: 0},
	{rededor2: 0},
	{Sprite155: 0},
	{Sprite160: 0},
	{ready: 0},
	{arrow2: 0},
	{arrowcamp: 0},
	{take1: 0},
	{take2: 0},
	{take3: 0},
	{take4: 0},
	{take5: 0},
	{score100: 0},
	{score101: 0},
	{score102: 0},
	{arrow2ok: 0},
	{camera: 0},
	{arrow4: 0},
	{arrow4ok: 0},
	{arrow1: 0},
	{arrow1ok: 0},
	{arrow3: 0},
	{arrow3ok: 0},
	{Line1a: 0},
	{Line1b: 0},
	{Line2a: 0},
	{Line2b: 0},
	{Line3a: 0},
	{Line3b: 0},
	{Line4a: 0},
	{Line4b: 0},
	{templatearrows: 0},
	{Sprite163: 0},
	{ScoreFonts: 0},
	{Sick: 0},
	{Sick2: 0},
	{Sick3: 0},
	{Sick4: 0},
	{Combo1: 0},
	{Combo2: 0},
	{set: 0},
	{go: 0},
	{Sprite164: 0},
	{Life: 0},
	{Sprite165: 0},
	{Sprite166: 0},
	{Sprite168: 0},
	{Particles21: 0},
	{Sprite345: 0},
	{Sprite170: 0},
	{Sprite171: 0},
	{Sprite172: 0},
	{Sprite173: 0},
	{Sprite174: 0},
	{Sprite175: 0},
	{Sprite178: 0},
	{Sprite181: 0},
	{Sprite346: 0},
	{Sprite347: 0},
	{m1: 0},
	{m2: 0},
	{m3: 0},
	{m4: 0},
	{Sprite348: 0},
	{Sprite349: 0},
	{Sprite350: 0},
	{Sprite351: 0},
	{Sprite352: 0},
	{Sprite353: 0},
	{Sprite354: 0},
	{Sprite355: 0},
	{Sprite356: 0},
	{Sprite357: 0},
	{Sprite358: 0},
	{Sprite359: 0},
	{Sprite360: 0},
	{Sprite361: 0},
	{Sprite362: 0},
	{Sprite363: 0},
	{highfont: 0},
	{highfont2: 0},
	{highfont3: 0},
	{highfont4: 0},
	{highfont5: 0},
	{highfont6: 0},
	{Particles22: 0},
	{Particles23: 0},
	{Particles24: 0},
	{ARROWKEYS: 0},
	{ARROWKEYS2: 0},
	{Sprite253: 0},
	{Sprite254: 0},
	{Sprite255: 0},
	{Sprite143: 0},
	{Sprite161: 0},
	{Sprite258: 0},
	{Sprite364: 0},
	{Sprite365: 0},
	{Sprite366: 0},
	{Sprite367: 0},
	{Sprite368: 0},
	{Sprite369: 0},
	{Sprite370: 0},
	{la3: 0},
	{la1: 0},
	{la4: 0},
	{la2: 0},
	{la5: 0},
	{la6: 0},
	{la10: 0},
	{highfont8: 0},
	{la9: 0},
	{la8: 0},
	{la11: 0},
	{highfont11: 0},
	{highfont12: 0},
	{la7: 0},
	{la12: 0},
	{highfont9: 0},
	{highfont7: 0},
	{highfont10: 0},
	{Sprite371: 0},
	{Sprite372: 0},
	{Sprite373: 0},
	{Sprite374: 0},
	{Sprite: 0},
	{Sprite375: 0},
	{Sprite376: 0},
	{Sprite377: 0},
	{Sprite378: 0},
	{Sprite379: 0},
	{Sprite380: 0},
	{Sprite381: 0},
	{LocalStorage: 0},
	{Sprite15: 0},
	{Sprite22: 0},
	{Sprite25: 0},
	{Tween: 0},
	{MainPopsicle: 0},
	{char2: 0},
	{char3: 0},
	{char5: 0},
	{char4: 0},
	{char6: 0},
	{char8: 0},
	{char3s: 0},
	{k10bk: 0},
	{forek10: 0},
	{k10logo: 0},
	{kloading: 0},
	{GameDistributionSDK: 0},
	{Sprite382: 0},
	{Sprite383: 0},
	{Rews: 0},
	{Family4: 0},
	{Family1: 0},
	{Family3: 0},
	{Family5: 0},
	{takes: 0},
	{Family7: 0},
	{Family8: 0},
	{sonido: 0},
	{achieve16: 0},
	{achieve15: 0},
	{achieve14: 0},
	{achieve13: 0},
	{achieve12: 0},
	{achieve11: 0},
	{achieve10: 0},
	{achieve9: 0},
	{achieve8: 0},
	{achieve7: 0},
	{achieve6: 0},
	{achieve5: 0},
	{achieve4: 0},
	{achieve3: 0},
	{achieve2: 0},
	{achieve1: 0},
	{IsScreenRotate: 0},
	{Endmusic: 0},
	{Combotime: 0},
	{Combos: 0},
	{vidas: 0},
	{speed: 0},
	{win: 0},
	{enemyon: 0},
	{perdedores: 0},
	{lavacount: 0},
	{contadoragua: 0},
	{losecount: 0},
	{toucher: 0},
	{Levelunlocker4: 0},
	{Levelunlocker3: 0},
	{Levelunlocker2: 0},
	{Levelunlocker: 0},
	{Bulletcount: 0},
	{maxbullets: 0},
	{failed: 0},
	{weaponselected: 0},
	{endlevel: 0},
	{damage: 0},
	{maxvida: 0},
	{levelnumber: 0},
	{vidaleft: 0},
	{Bulletsleft: 0},
	{shoot: 0},
	{guntype: 0},
	{speedupgrade: 0},
	{Score: 0},
	{colortype: 0},
	{adss: 0},
	{Combo: 0},
	{ads: 0},
	{complete: 0},
	{weapon16: 0},
	{weapon15: 0},
	{weapon14: 0},
	{weapon13: 0},
	{weapon12: 0},
	{weapon11: 0},
	{weapon10: 0},
	{weapon9: 0},
	{weapon8: 0},
	{weapon7: 0},
	{weapon6: 0},
	{weapon5: 0},
	{weapon4: 0},
	{weapon3: 0},
	{weapon2: 0},
	{BestScore: 0},
	{Beststage: 0},
	{gifttime: 0},
	{gifts: 0},
	{gameover: 0},
	{Skins: 0},
	{Leveltype: 0},
	{endstars: 0},
	{globalStars: 0},
	{level20star2: 0},
	{level20star: 0},
	{level21star: 0},
	{level22star: 0},
	{level23star: 0},
	{level24star: 0},
	{level25star: 0},
	{level19star: 0},
	{level18star: 0},
	{level17star: 0},
	{level16star: 0},
	{level15star: 0},
	{level14star: 0},
	{level13star: 0},
	{level12star: 0},
	{level11star: 0},
	{level10star: 0},
	{level9star: 0},
	{level8star: 0},
	{level7star: 0},
	{level6star: 0},
	{level5star: 0},
	{level4star: 0},
	{level3star: 0},
	{level2star: 0},
	{level1star: 0},
	{shots: 0},
	{Fuits: 0},
	{Stage: 0},
	{ShotsLeft: 0},
	{Level12score: 0},
	{Level11score: 0},
	{Level10score: 0},
	{Level9score: 0},
	{Level8score: 0},
	{Level7score: 0},
	{Level6score: 0},
	{Level5score: 0},
	{Level4score: 0},
	{Level3score: 0},
	{Level2score: 0},
	{Level1score: 0},
	{week6score: 0},
	{week5score: 0},
	{week4score: 0},
	{week3score: 0},
	{week2score: 0},
	{week1score: 0},
	{level50star: 0},
	{level49star: 0},
	{level48star: 0},
	{level47star: 0},
	{level46star: 0},
	{level45star: 0},
	{level44star: 0},
	{level43star: 0},
	{level42star: 0},
	{level41star: 0},
	{level40star: 0},
	{level39star: 0},
	{level38star: 0},
	{level37star: 0},
	{level36star: 0},
	{level35star: 0},
	{level34star: 0},
	{level33star: 0},
	{level32star: 0},
	{level31star: 0},
	{level30star: 0},
	{level29star: 0},
	{level28star: 0},
	{level27star: 0},
	{level26star: 0},
	{addbullets: 0},
	{adddamage: 0},
	{bulletsprice: 0},
	{damageprice: 0},
	{buybullets: 0},
	{buydamage: 0},
	{money2: 0},
	{boots: 0},
	{randomunlock: 0}
];

self.InstanceType = {
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	LiveFont3: class extends self.ISpriteFontInstance {},
	LiveFont4: class extends self.ISpriteFontInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	LiveFont5: class extends self.ISpriteFontInstance {},
	shot1: class extends self.ISpriteInstance {},
	shot2: class extends self.ISpriteInstance {},
	shot3: class extends self.ISpriteInstance {},
	shot4: class extends self.ISpriteInstance {},
	shot5: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	LiveFont6: class extends self.ISpriteFontInstance {},
	LiveFont7: class extends self.ISpriteFontInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Rueda: class extends self.ISpriteInstance {},
	shot13: class extends self.ISpriteInstance {},
	shot14: class extends self.ISpriteInstance {},
	shot15: class extends self.ISpriteInstance {},
	piece1: class extends self.ISpriteInstance {},
	piece4: class extends self.ISpriteInstance {},
	piece5: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	piece2: class extends self.ISpriteInstance {},
	piece6: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	fontmoney1: class extends self.ISpriteFontInstance {},
	LiveFont9: class extends self.ISpriteFontInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	ruedas: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Browser: class extends self.IInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	selector: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Particles7: class extends self.IParticlesInstance {},
	LiveFont10: class extends self.ISpriteFontInstance {},
	p1: class extends self.IParticlesInstance {},
	p2: class extends self.IParticlesInstance {},
	p3: class extends self.IParticlesInstance {},
	p4: class extends self.IParticlesInstance {},
	p5: class extends self.IParticlesInstance {},
	p6: class extends self.IParticlesInstance {},
	p7: class extends self.IParticlesInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	LiveFont11: class extends self.ISpriteFontInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	s49: class extends self.ISpriteInstance {},
	s52: class extends self.ISpriteInstance {},
	s55: class extends self.ISpriteInstance {},
	s61: class extends self.ISpriteInstance {},
	s62: class extends self.ISpriteInstance {},
	s63: class extends self.ISpriteInstance {},
	s64: class extends self.ISpriteInstance {},
	s66: class extends self.ISpriteInstance {},
	s67: class extends self.ISpriteInstance {},
	s69: class extends self.ISpriteInstance {},
	s70: class extends self.ISpriteInstance {},
	s71: class extends self.ISpriteInstance {},
	s72: class extends self.ISpriteInstance {},
	restart2: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	s73: class extends self.ISpriteInstance {},
	s74: class extends self.ISpriteInstance {},
	s75: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	pinner: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Particles8: class extends self.IParticlesInstance {},
	Particles9: class extends self.IParticlesInstance {},
	Particles10: class extends self.IParticlesInstance {},
	Particles11: class extends self.IParticlesInstance {},
	Particles12: class extends self.IParticlesInstance {},
	Particles13: class extends self.IParticlesInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	LiveFont12: class extends self.ISpriteFontInstance {},
	LiveFont13: class extends self.ISpriteFontInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	Sprite114: class extends self.ISpriteInstance {},
	Sprite115: class extends self.ISpriteInstance {},
	Sprite116: class extends self.ISpriteInstance {},
	Sprite117: class extends self.ISpriteInstance {},
	LiveFont14: class extends self.ISpriteFontInstance {},
	LiveFont15: class extends self.ISpriteFontInstance {},
	Sprite118: class extends self.ISpriteInstance {},
	Sprite119: class extends self.ISpriteInstance {},
	Sprite120: class extends self.ISpriteInstance {},
	Sprite121: class extends self.ISpriteInstance {},
	Sprite122: class extends self.ISpriteInstance {},
	Sprite123: class extends self.ISpriteInstance {},
	LiveFont16: class extends self.ISpriteFontInstance {},
	soundsprite: class extends self.ISpriteInstance {},
	walksprite: class extends self.ISpriteInstance {},
	Sprite138: class extends self.ISpriteInstance {},
	Sprite139: class extends self.ISpriteInstance {},
	Particles14: class extends self.IParticlesInstance {},
	Particles15: class extends self.IParticlesInstance {},
	p8: class extends self.IParticlesInstance {},
	p9: class extends self.IParticlesInstance {},
	p10: class extends self.IParticlesInstance {},
	p11: class extends self.IParticlesInstance {},
	p12: class extends self.IParticlesInstance {},
	p13: class extends self.IParticlesInstance {},
	RESET: class extends self.ISpriteInstance {},
	YES: class extends self.ISpriteInstance {},
	NO: class extends self.ISpriteInstance {},
	mira: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Particles16: class extends self.IParticlesInstance {},
	Particles17: class extends self.IParticlesInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	sangre3: class extends self.ISpriteInstance {},
	sangre1: class extends self.ISpriteInstance {},
	sangre2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	fonder: class extends self.ISpriteInstance {},
	continue: class extends self.ISpriteInstance {},
	cancel: class extends self.ISpriteInstance {},
	restarted: class extends self.ISpriteInstance {},
	freemoney: class extends self.ISpriteInstance {},
	fonder2: class extends self.ISpriteInstance {},
	continue2: class extends self.ISpriteInstance {},
	cancel2: class extends self.ISpriteInstance {},
	restarted2: class extends self.ISpriteInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	Sprite111: class extends self.ISpriteInstance {},
	Particles18: class extends self.IParticlesInstance {},
	Sprite129: class extends self.ISpriteInstance {},
	redbullet: class extends self.ISpriteInstance {},
	Sprite130: class extends self.ISpriteInstance {},
	Sprite134: class extends self.ISpriteInstance {},
	Sprite146: class extends self.ISpriteInstance {},
	Sprite147: class extends self.ISpriteInstance {},
	Sprite148: class extends self.ISpriteInstance {},
	Sprite150: class extends self.ISpriteInstance {},
	Sprite152: class extends self.ISpriteInstance {},
	Sprite156: class extends self.ISpriteInstance {},
	Sprite157: class extends self.ISpriteInstance {},
	Sprite158: class extends self.ISpriteInstance {},
	Sprite162: class extends self.ISpriteInstance {},
	LiveFont17: class extends self.ISpriteFontInstance {},
	Sprite167: class extends self.ISpriteInstance {},
	Sprite176: class extends self.ISpriteInstance {},
	Sprite189: class extends self.ISpriteInstance {},
	Sprite194: class extends self.ISpriteInstance {},
	Sprite195: class extends self.ISpriteInstance {},
	Sprite196: class extends self.ISpriteInstance {},
	Sprite197: class extends self.ISpriteInstance {},
	Sprite199: class extends self.ISpriteInstance {},
	Sprite200: class extends self.ISpriteInstance {},
	Sprite201: class extends self.ISpriteInstance {},
	Sprite202: class extends self.ISpriteInstance {},
	Sprite203: class extends self.ISpriteInstance {},
	Sprite204: class extends self.ISpriteInstance {},
	Sprite205: class extends self.ISpriteInstance {},
	Sprite206: class extends self.ISpriteInstance {},
	Sprite207: class extends self.ISpriteInstance {},
	Sprite208: class extends self.ISpriteInstance {},
	Sprite209: class extends self.ISpriteInstance {},
	Sprite222: class extends self.ISpriteInstance {},
	Sprite223: class extends self.ISpriteInstance {},
	Sprite224: class extends self.ISpriteInstance {},
	freemoney2: class extends self.ISpriteInstance {},
	Sprite229: class extends self.ISpriteInstance {},
	Sprite230: class extends self.ISpriteInstance {},
	moneyhud1: class extends self.ISpriteInstance {},
	moneyhud2: class extends self.ISpriteInstance {},
	fontmoney2: class extends self.ISpriteFontInstance {},
	Sprite231: class extends self.ISpriteInstance {},
	bulletcouns: class extends self.ISpriteFontInstance {},
	Sprite239: class extends self.ISpriteInstance {},
	Sprite240: class extends self.ISpriteInstance {},
	Sprite236: class extends self.ISpriteInstance {},
	Sprite241: class extends self.ISpriteInstance {},
	Sprite242: class extends self.ISpriteInstance {},
	POWER1: class extends self.ISpriteInstance {},
	POWER2: class extends self.ISpriteInstance {},
	Sprite250: class extends self.ISpriteInstance {},
	Sprite251: class extends self.ISpriteInstance {},
	Sprite252: class extends self.ISpriteInstance {},
	Particles19: class extends self.IParticlesInstance {},
	Sprite256: class extends self.ISpriteInstance {},
	Sprite257: class extends self.ISpriteInstance {},
	Sprite259: class extends self.ISpriteInstance {},
	Sprite260: class extends self.ISpriteInstance {},
	Sprite261: class extends self.ISpriteInstance {},
	paricreyas: class extends self.IParticlesInstance {},
	paricreyas2: class extends self.IParticlesInstance {},
	Particles20: class extends self.IParticlesInstance {},
	Sprite265: class extends self.ISpriteInstance {},
	Sprite270: class extends self.ISpriteInstance {},
	perdedor: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	MenuLightFlare: class extends self.ISpriteInstance {},
	Sprite243: class extends self.ISpriteInstance {},
	Sprite246: class extends self.ISpriteInstance {},
	Sprite249: class extends self.ISpriteInstance {},
	Sprite295: class extends self.ISpriteInstance {},
	Sprite296: class extends self.ISpriteInstance {},
	Sprite297: class extends self.ISpriteInstance {},
	Sprite298: class extends self.ISpriteInstance {},
	Sprite299: class extends self.ISpriteInstance {},
	Sprite300: class extends self.ISpriteInstance {},
	Sprite301: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	tuto: class extends self.ISpriteInstance {},
	rededor: class extends self.ISpriteInstance {},
	tuto2: class extends self.ISpriteInstance {},
	tuto3: class extends self.ISpriteInstance {},
	tuto4: class extends self.ISpriteInstance {},
	restarted3: class extends self.ISpriteInstance {},
	Sprite142: class extends self.ISpriteInstance {},
	Sprite144: class extends self.ISpriteInstance {},
	Sprite145: class extends self.ISpriteInstance {},
	Sprite149: class extends self.ISpriteInstance {},
	Sprite151: class extends self.ISpriteInstance {},
	rededor2: class extends self.ISpriteInstance {},
	Sprite155: class extends self.ISpriteInstance {},
	Sprite160: class extends self.ISpriteInstance {},
	arrow2: class extends self.ISpriteInstance {},
	arrowcamp: class extends self.ISpriteInstance {},
	take1: class extends self.ISpriteInstance {},
	take2: class extends self.ISpriteInstance {},
	take3: class extends self.ISpriteInstance {},
	take4: class extends self.ISpriteInstance {},
	take5: class extends self.ISpriteInstance {},
	score100: class extends self.ISpriteInstance {},
	score101: class extends self.ISpriteInstance {},
	score102: class extends self.ISpriteInstance {},
	arrow2ok: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	arrow4: class extends self.ISpriteInstance {},
	arrow4ok: class extends self.ISpriteInstance {},
	arrow1: class extends self.ISpriteInstance {},
	arrow1ok: class extends self.ISpriteInstance {},
	arrow3: class extends self.ISpriteInstance {},
	arrow3ok: class extends self.ISpriteInstance {},
	Line1a: class extends self.ISpriteInstance {},
	Line1b: class extends self.ISpriteInstance {},
	Line2a: class extends self.ISpriteInstance {},
	Line2b: class extends self.ISpriteInstance {},
	Line3a: class extends self.ISpriteInstance {},
	Line3b: class extends self.ISpriteInstance {},
	Line4a: class extends self.ISpriteInstance {},
	Line4b: class extends self.ISpriteInstance {},
	templatearrows: class extends self.ISpriteInstance {},
	Sprite163: class extends self.ISpriteInstance {},
	ScoreFonts: class extends self.ISpriteFontInstance {},
	Sick: class extends self.ISpriteInstance {},
	Sick2: class extends self.ISpriteInstance {},
	Sick3: class extends self.ISpriteInstance {},
	Sick4: class extends self.ISpriteInstance {},
	Combo1: class extends self.ISpriteInstance {},
	Combo2: class extends self.ISpriteInstance {},
	ready: class extends self.ISpriteInstance {},
	set: class extends self.ISpriteInstance {},
	go: class extends self.ISpriteInstance {},
	Sprite164: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteInstance {},
	Sprite165: class extends self.ISpriteInstance {},
	Sprite166: class extends self.ISpriteInstance {},
	Sprite168: class extends self.ISpriteInstance {},
	Particles21: class extends self.IParticlesInstance {},
	Sprite345: class extends self.ISpriteInstance {},
	Sprite170: class extends self.ISpriteInstance {},
	Sprite171: class extends self.ISpriteInstance {},
	Sprite172: class extends self.ISpriteInstance {},
	Sprite173: class extends self.ISpriteInstance {},
	Sprite174: class extends self.ISpriteInstance {},
	Sprite175: class extends self.ISpriteInstance {},
	Sprite178: class extends self.ISpriteInstance {},
	Sprite181: class extends self.ISpriteInstance {},
	Sprite346: class extends self.ISpriteInstance {},
	Sprite347: class extends self.ISpriteInstance {},
	m1: class extends self.ISpriteInstance {},
	m2: class extends self.ISpriteInstance {},
	m3: class extends self.ISpriteInstance {},
	m4: class extends self.ISpriteInstance {},
	Sprite348: class extends self.ISpriteInstance {},
	Sprite349: class extends self.ISpriteInstance {},
	Sprite350: class extends self.ISpriteInstance {},
	Sprite351: class extends self.ISpriteInstance {},
	Sprite352: class extends self.ISpriteInstance {},
	Sprite353: class extends self.ISpriteInstance {},
	Sprite354: class extends self.ISpriteInstance {},
	Sprite355: class extends self.ISpriteInstance {},
	Sprite356: class extends self.ISpriteInstance {},
	Sprite357: class extends self.ISpriteInstance {},
	Sprite358: class extends self.ISpriteInstance {},
	Sprite359: class extends self.ISpriteInstance {},
	Sprite360: class extends self.ISpriteInstance {},
	Sprite361: class extends self.ISpriteInstance {},
	Sprite362: class extends self.ISpriteInstance {},
	Sprite363: class extends self.ISpriteInstance {},
	highfont: class extends self.ISpriteFontInstance {},
	highfont2: class extends self.ISpriteFontInstance {},
	highfont3: class extends self.ISpriteFontInstance {},
	highfont4: class extends self.ISpriteFontInstance {},
	highfont5: class extends self.ISpriteFontInstance {},
	highfont6: class extends self.ISpriteFontInstance {},
	Particles22: class extends self.IParticlesInstance {},
	Particles23: class extends self.IParticlesInstance {},
	Particles24: class extends self.IParticlesInstance {},
	ARROWKEYS: class extends self.ISpriteInstance {},
	ARROWKEYS2: class extends self.ISpriteInstance {},
	Sprite253: class extends self.ISpriteInstance {},
	Sprite254: class extends self.ISpriteInstance {},
	Sprite255: class extends self.ISpriteInstance {},
	Sprite143: class extends self.ISpriteInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite258: class extends self.ISpriteInstance {},
	Sprite364: class extends self.ISpriteInstance {},
	Sprite365: class extends self.ISpriteInstance {},
	Sprite366: class extends self.ISpriteInstance {},
	Sprite367: class extends self.ISpriteInstance {},
	Sprite368: class extends self.ISpriteInstance {},
	Sprite369: class extends self.ISpriteInstance {},
	Sprite370: class extends self.ISpriteInstance {},
	la3: class extends self.ISpriteInstance {},
	la1: class extends self.ISpriteInstance {},
	la4: class extends self.ISpriteInstance {},
	la2: class extends self.ISpriteInstance {},
	la5: class extends self.ISpriteInstance {},
	la6: class extends self.ISpriteInstance {},
	la10: class extends self.ISpriteInstance {},
	highfont8: class extends self.ISpriteFontInstance {},
	la9: class extends self.ISpriteInstance {},
	la8: class extends self.ISpriteInstance {},
	la11: class extends self.ISpriteInstance {},
	highfont11: class extends self.ISpriteFontInstance {},
	highfont12: class extends self.ISpriteFontInstance {},
	la7: class extends self.ISpriteInstance {},
	la12: class extends self.ISpriteInstance {},
	highfont9: class extends self.ISpriteFontInstance {},
	highfont7: class extends self.ISpriteFontInstance {},
	highfont10: class extends self.ISpriteFontInstance {},
	Sprite371: class extends self.ISpriteInstance {},
	Sprite372: class extends self.ISpriteInstance {},
	Sprite373: class extends self.ISpriteInstance {},
	Sprite374: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite375: class extends self.ISpriteInstance {},
	Sprite376: class extends self.ISpriteInstance {},
	Sprite377: class extends self.ISpriteInstance {},
	Sprite378: class extends self.ISpriteInstance {},
	Sprite379: class extends self.ISpriteInstance {},
	Sprite380: class extends self.ISpriteInstance {},
	Sprite381: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	MainPopsicle: class extends self.ISpriteInstance {},
	char2: class extends self.ISpriteInstance {},
	char3: class extends self.ISpriteInstance {},
	char5: class extends self.ISpriteInstance {},
	char4: class extends self.ISpriteInstance {},
	char6: class extends self.ISpriteInstance {},
	char8: class extends self.ISpriteInstance {},
	char3s: class extends self.ISpriteInstance {},
	k10bk: class extends self.ITiledBackgroundInstance {},
	forek10: class extends self.ISpriteInstance {},
	k10logo: class extends self.ISpriteInstance {},
	kloading: class extends self.ISpriteInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	Sprite382: class extends self.ISpriteInstance {},
	Sprite383: class extends self.ISpriteInstance {},
	Rews: class extends self.ISpriteInstance {},
	Family4: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {},
	Family3: class extends self.ISpriteInstance {},
	Family5: class extends self.ISpriteInstance {},
	takes: class extends self.ISpriteInstance {},
	Family7: class extends self.ISpriteInstance {},
	Family8: class extends self.ISpriteInstance {}
}